### ISSUE TITLE
dwmblocks modules

### ISSUE THREAD

**Issue by kronikpillow** [torrinfail/dwmblocks#2]
hi there, been looking to chekout various dwmblock builds, where can I find your statusbar modules/scripts etc that you are using in your dwmblocks build?

**Comment by torrinfail** [comment]
Here's my scripts for when I'm on Arch Linux. 
[statusbar.tar.gz](https://github.com/torrinfail/dwmblocks/files/3970495/statusbar.tar.gz)

And here's the scripts I use to change volume and such that signal dwmblocks.
[statusbarkeybinds.tar.gz](https://github.com/torrinfail/dwmblocks/files/3970514/statusbarkeybinds.tar.gz)

I don't have my dotfiles on github because I don't want to have to make sure they're portable or make any sense. I'm not sure if it's at all known but I'm the original author of dwmblocks. I should really change the default blocks.h file to reference posix commands just so people can use this program out of the box. I honestly didn't realize people were using dwmblocks until a little while ago. I kinda just wrote it for my own usage. I have been updating it to be more portable with the BSDs and such. I should probably make the documentation better as well.

Have a good one.

-Torrinfail

**Comment by kronikpillow** [comment]
Nice thanks :) well anyone who uses Luke Smith's LARBS gets a i3 and dwm+dwmblocks installed :) I have a few suggestions if i might add :) like font support ... I use the following script to get what song is playing [luke
s musick i3blocks block](https://github.com/LukeSmithxyz/voidrice/blob/master/.local/bin/statusbar/music) ... on i3blocks it displays it in italic font, while on dwmblocks it ignores the font settings and shows the code around the song name ...


another awesome thing would be if it is possible to make blocks clickable like in i3blocks?
